### ISSUE TITLE
Packaging with the DLL files bundled into the exe?

### ISSUE THREAD

**Issue by KovaaK** [Zergatul/Zergatul.Obs.InputOverlay#1]
Heya!  I started from your source code to make a little Doom Eternal-specific overlay, and I got the functionality working quite well, but I'm wondering what approach you used to package your C# app without having 356 extra files in the same folder as the application.

**Comment by Zergatul** [comment]
You can see in `.csproj` file next properties:

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>

Then I run from VS: right click on project in solution explorer -> Publish. It shows additional page with some settings. And there is Publish button for single publish profile.

**Comment by KovaaK** [comment]
Got it!  Thank you very much :D.
And a small teaser of a high end Doom Eternal guy using the new app:
https://streamable.com/2bl9o3
https://streamable.com/euzswz

Will make a proper fork in Github soon and release it when I have a chance.  Thank you very much for your help and the base code to make this possible - very slick little project you made :)
