### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ImaKiller1999** [Zergatul/Zergatul.Obs.InputOverlay#10]
I would like to add Mouse motion to my overlay. How would I do that? Was also wondering how to add extra letters to the overlay? I would really like the letter {T} added because I use that keybind a lot in games. One more question, When I click into OBS the overlay freezes. Is that a normal thing or am I doing something wrong?

**Comment by Zergatul** [comment]
To add Mouse motion, check https://github.com/Zergatul/Zergatul.Obs.InputOverlay/blob/master/docs/Modules.md page, it contains brief description of all modules. In short you need to add Browser source wit URL: `http://localhost:5001/mouse-movement.html`.
To add extra letters open `default-keyboard.html` from `wwwroot` folder in text editor, scroll to the end. You will find HTML layout here. Adding new key should be straightforward and shouldn't require knowledge of HTML. Button T is already here, it is just hidden. Remove `hidden` from class list.
About freezing. If you are running executable with non-admin, but OBS with admin privileges, program is unable to catch inputs done in applications running as admin. This is how security in Windows is organized.

**Comment by ImaKiller1999** [comment]
Thank you! This is the best overlay i've seen so far. Great work!

**Comment by ImaKiller1999** [comment]
@Zergatul So i'm having this problem now where T is showing but I tried to show H and Number 5 but neither are working. I checked the code to make sure I didn't add any extra things including spaces or anything and I matched the code to other letters and number but these don't seem to work.

**Comment by Zergatul** [comment]
Could you share your `default-keyboard.html`?

**Comment by ImaKiller1999** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            /*background-color: black;*/ /* uncomment to this to debug in browser */
            margin: 0;
            padding: 0;
            overflow: hidden;
        }
        .hidden {
            display: none !important;
        }
        div.container {
            display: block;
            white-space: nowrap;
        }
        div.keyboard {
            display: inline-block;
            margin: 10px;
        }
        div.mouse {
            display: inline-block;
            margin: 10px;
        }
        div.mouse > svg {
            width: 200px;
        }
        div.button,
        div.small-button,
        div.tab-button,
        div.caps-button,
        div.shift-button,
        div.ctrl-button,
        div.alt-button,
        div.space-button {
            border: 2px solid white;
            border-radius: 10px;
            color: white;
            display: inline-block;
            font-family: Calibri;
            font-size: 20px;
            line-height: 40px;
            height: 40px;
            text-align: center;
            width: 40px;
        }
        div.small-button {
            line-height: 30px;
            height: 30px;
        }
        div.tab-button {
            width: 60px;
        }
        div.caps-button {
            width: 70px;
        }
        div.shift-button {
            width: 90px;
        }
        div.ctrl-button {
            width: 60px;
        }
        div.alt-button {
            width: 60px;
        }
        div.space-button {
            width: 280px;
        }
        div.pressed {
            background-color: #2DA026; /* key pressed color */
            box-shadow: 0 0 8px 3px rgba(35, 173, 278, 1); /* glow effect while holding key */
        }
        div.white-space {
            border: 2px solid transparent;
            display: inline-block;
            width: 40px;
        }
        div.line {
            height: 5px;
        }
        div.big-line {
            height: 15px;
        }
        div.released {
            animation: key-released 0.5s ease-out; /* animation settings for key releasing */
        }
        @keyframes key-released {
            from {
                background-color: #96CF13; /* key released color */
            }
            to {
                background-color: transparent;
            }
        }
    </style>
    <script>
        function listenWebSocket() {
            let state = {};
            let ws = new WebSocket('ws://' + location.host + '/ws');
            ws.onopen = function () {
                ws.send(JSON.stringify({ listen: 'Keyboard' }));
            };
            ws.onmessage = function (event) {
                let data = JSON.parse(event.data);

                if (data.type == 'Ping') {
                    // reply to ping messages
                    ws.send(JSON.stringify({ ping: data.ping }));
                    return;
                }

                if (data.type == 'Keyboard') {
                    if (data.pressed) {
                        state[data.button] = true;
                        let element = document.getElementById(data.button);
                        if (element) {
                            element.classList.remove('released');
                            element.classList.add('pressed');
                        }
                    } else {
                        if (state[data.button]) {
                            delete state[data.button];
                            let element = document.getElementById(data.button);
                            if (element) {
                                element.classList.remove('pressed');
                                element.classList.add('released');
                            }
                        }
                    }
                }
            };
        }

        document.addEventListener('DOMContentLoaded', function () {
            listenWebSocket();
        });

    </script>
</head>
<body>
    <div class="keyboard">
        <div>
            <div class="button small-button" id="Esc">Esc</div>
            <div class="white-space"></div>
            <div class="button small-button" id="F1">F1</div>
            <div class="button small-button hidden" id="F2">F2</div>
            <div class="button small-button hidden" id="F3">F3</div>
            <div class="button small-button hidden" id="F4">F4</div>
        </div>
        <div class="big-line"></div>
        <div>
            <div class="button" id="Tilde">~</div>
            <div class="button" id="Key1">1</div>
            <div class="button" id="Key2">2</div>
            <div class="button" id="Key3">3</div>
            <div class="button" id="Key4">4</div>
            <div class="button" id="Key5">5</div>
            <div class="button hidden" id="Key6">6</div>
            <div class="button hidden" id="Key7">7</div>
            <div class="button hidden" id="Key8">8</div>
        </div>
        <div class="line"></div>
        <div>
            <div class="button tab-button" id="Tab">Tab</div>
            <div class="button" id="KeyQ">Q</div>
            <div class="button" id="KeyW">W</div>
            <div class="button" id="KeyE">E</div>
            <div class="button" id="KeyR">R</div>
            <div class="button" id="KeyT">T</div>
            <div class="button" id="KeyY">Y</div>
            <div class="button hidden" id="KeyU">U</div>
            <div class="button hidden" id="KeyI">I</div>
        </div>
        <div class="line"></div>
        <div>
            <div class="button caps-button" id="CapsLock">Caps</div>
            <div class="button" id="KeyA">A</div>
            <div class="button" id="KeyS">S</div>
            <div class="button" id="KeyD">D</div>
            <div class="button" id="KeyF">F</div>
            <div class="button" id="KeyG">G</div>
            <div class="button" id="KeyH">H</div>
            <div class="button hidden" id="KeyJ">J</div>
            <div class="button hidden" id="KeyK">K</div>
        </div>
        <div class="line"></div>
        <div>
            <div class="button shift-button" id="LeftShift">Shift</div>
            <div class="button" id="KeyZ">Z</div>
            <div class="button" id="KeyX">X</div>
            <div class="button" id="KeyC">C</div>
            <div class="button" id="KeyV">V</div>
            <div class="button" id="KeyB">B</div>
            <div class="button hidden" id="KeyN">N</div>
            <div class="button hidden" id="KeyM">M</div>
        </div>
        <div class="line"></div>
        <div>
            <div class="button ctrl-button" id="LeftCtrl">Ctrl</div>
            <div class="white-space"></div>
            <div class="button alt-button" id="LeftAlt">Alt</div>
            <div class="button space-button" id="Space">Space</div>
        </div>
    </div>
</body>
</html>

**Comment by ImaKiller1999** [comment]
How would I do that without copying the text file?

**Comment by Zergatul** [comment]
You can upload it to some text sharing service like https://pastebin.com/

**Comment by ImaKiller1999** [comment]
https://pastebin.com/NJTKayxz

**Comment by Zergatul** [comment]
Your file works perfectly fine for me. You can try "Refresh cache of current page" button in Browser source settings

**Comment by ImaKiller1999** [comment]
I got it working thanks. I just redownloaded the file and changed it now it works. Weird.
