### ISSUE TITLE
Zergatul.Obs.InputOverlay.exe opens and crashes

### ISSUE THREAD

**Issue by cybercuate** [Zergatul/Zergatul.Obs.InputOverlay#11]
When I open Zergatul.Obs.InputOverlay.exe it just crashes on windows 11
![Captura de pantalla (2)](https://user-images.githubusercontent.com/46688955/166615941-1479cf25-abfd-43f2-860a-0e62b9e278bd.png)

**Comment by Zergatul** [comment]
Do you have Xbox360 controller or it is 3rd party gamepad which reports it is Xbox360?

**Comment by Zergatul** [comment]
Please check new release. It will not fix a problem with RawInput API for your gamepad, but app should no longer crash (you will  still see an error in the log). You should be able to use XInput API files (ending with `-XInput.html`). Please provide new log (I added additional detail).

**Comment by cybercuate** [comment]
> Do you have Xbox360 controller or it is 3rd party gamepad which reports it is Xbox360?

I use a Wii U Pro controller via bluetooth usb using WiinUSoft. This makes the gamepad itself as the primary(0) gamepad on windows and it creates a virtual Xbox360 gamepad as a seconday(1) controller. I just choose windows to prefer the virtual Xbox360 as primary and it has been working awesome for years. No compatibilty issues with any game. Also, even tho your programs shows the xbox360 controller running OBS shows black screen and firefox just white screen, and your "multiple gamepads" page is down.


![Captura de pantalla (6)](https://user-images.githubusercontent.com/46688955/166697148-e49bc379-8cb9-4dc6-a728-88c80bd2e293.png)

**Comment by Zergatul** [comment]
Thanks for the details! This emulator may not work correctly with RawInput API, which is fine, and games prefer to use XInput over RawInput (that's why it worked fine in games for you).

From your log I see: `Content root path: C:\Users\cyber\Documents\OBS1`. Did you unzip archive to this directory? Does it contain wwwroot directory with html files?

**Comment by Zergatul** [comment]
> and your "multiple gamepads" page is down.

I just tried to use link from main page, and it works: https://github.com/Zergatul/Zergatul.Obs.InputOverlay/blob/master/docs/MultipleGamepads.md

**Comment by cybercuate** [comment]
> Thanks for the details! This emulator may not work correctly with RawInput API, which is fine, and games prefer to use XInput over RawInput (that's why it worked fine in games for you).
> 
> From your log I see: `Content root path: C:\Users\cyber\Documents\OBS1`. Did you unzip archive to this directory? Does it contain wwwroot directory with html files?

Yes, it is there and is an empty folder. So, I had to manually extract the content from the folder inside the zip file because windows 11. **_Now is working PERFECT._** I just need a WiiU pro controller overlay that I will attemp to make it by my own or if you have a tool to make new overlays please let me know.

And at https://github.com/Zergatul/Zergatul.Obs.InputOverlay/blob/master/docs/Modules.md#gamepads where it says "[Using multiple gamepads](https://github.com/Zergatul/Zergatul.Obs.InputOverlay/blob/master/docs/docs/MultipleGamepads.md). It has a .../docs/docs... url, thats why I get the "not found" error.

**Comment by Zergatul** [comment]
Right, this link was broken, I fixed it, thanks!

> I just need a WiiU pro controller overlay that I will attemp to make it by my own or if you have a tool to make new overlays please let me know.

Did you check this? https://github.com/Zergatul/Zergatul.Obs.InputOverlay/blob/master/docs/CustomizingMouse.md It says mouse, because this doc has been written before gamepads support. But general ideas are the same: you need to pay attention at SVG element IDs.

**Comment by cybercuate** [comment]
> Right, this link was broken, I fixed it, thanks!
> 
> > I just need a WiiU pro controller overlay that I will attemp to make it by my own or if you have a tool to make new overlays please let me know.
> 
> Did you check this? https://github.com/Zergatul/Zergatul.Obs.InputOverlay/blob/master/docs/CustomizingMouse.md It says mouse, because this doc has been written before gamepads support. But general ideas are the same: you need to pay attention at SVG element IDs.

Well I tried making the wiiU pro controller but it doesn't work. Nothing moves but the gamepad picture shows on obs. Here you have the files I made and if you can fix it and add it to your main build would be awesome. Also, I can provide the raw vectors if you need them.

[WiiUPro-XInput.zip](https://github.com/Zergatul/Zergatul.Obs.InputOverlay/files/8627321/WiiUPro-XInput.zip)

**Comment by Zergatul** [comment]
I quickly checked your SVG. Page unable to find elements D0-D7 (for dpad). There may be other problems, please compare it with original SVG. Or I may fix it some time later.

**Comment by cybercuate** [comment]
> I quickly checked your SVG. Page unable to find elements D0-D7 (for dpad). There may be other problems, please compare it with original SVG. Or I may fix it some time later.

Hey I made it, you can have the files to put in the master build if you want.
[WiiUProController-XInput.zip](https://github.com/Zergatul/Zergatul.Obs.InputOverlay/files/8635385/WiiUProController-XInput.zip)

And I have a new problem. Whenever I press the sticks as buttons the color fill changes to transparent after turning green. I need the sticks to be white when not pressed and green (as it is working) when pressed. I tried make it bitmaps but only the borders seem to stay white.
![Animation](https://user-images.githubusercontent.com/46688955/167009166-363a7482-b9fd-4d04-8e76-4bd7b7f83597.gif)

**Comment by Zergatul** [comment]
Could you create pull request and add your files? I will think about white sticks, it will require changes in javascript code, since it fills all elements with transparent color when button is unpressed.

**Comment by Zergatul** [comment]
[WiiUProController-XInput.zip](https://github.com/Zergatul/Zergatul.Obs.InputOverlay/files/8635508/WiiUProController-XInput.zip)
This was simpler than I expected. Check this updated html file

**Comment by cybercuate** [comment]
> Could you create pull request and add your files? I will think about white sticks, it will require changes in javascript code, since it fills all elements with transparent color when button is unpressed.

Sorry I don't know how to use github, I just post like on any other forum.

> [WiiUProController-XInput.zip](https://github.com/Zergatul/Zergatul.Obs.InputOverlay/files/8635508/WiiUProController-XInput.zip) This was simpler than I expected. Check this updated html file

Yup is working **_but_** as I am changing the opacity of the objects the color (green when pressed) only on the sticks get affected too (by the opacity of the fill of the object). Every other button has transparent fill and only the borders have some opacity value. Maybe thats why they are not affected. I tried values from 1 to 30 and is not blending the colors (white+green). It is reducing the opacity of green too.
![wpxinput](https://user-images.githubusercontent.com/46688955/167021556-6edee4a6-be7f-40a1-92ad-d9e9a7d553c2.png)

**Comment by Zergatul** [comment]
What are you trying to achieve?

**Comment by cybercuate** [comment]
> What are you trying to achieve?

not using filters in OBS. Because sometimes OBS decides to use a lot of CPU or GPU, so, I tought why not only reducing opacity on the SVGs or PNGs overlays. Besides, when I press something, with filters on, the color is also reduced. So, what would be the point of having a barely visible overlay if no one can see what you are pressing exactly? (maybe thats why most of streamers don't use it). Also, I would like to change to different colors depending on what button is pressed. OBS without filters is the best and only way to avoid random high CPU/GPU usage. Your program is working good now as it is. The others are the extras I'd put if I know about programing

**Comment by Zergatul** [comment]
In CSS you can change opacity for entire page. Find `<style>` tag, and add `opacity: 0.5;` to `body`, like below:
```
body {
    /*background-color: black;*/ /* uncomment to this to debug in browser */
    margin: 0;
    padding: 0;
    overflow: hidden;
    opacity: 0.5;
}
```

Anyway I am still confused. I tried to reduce opacity in SVG for buttons and for stick cores, and they behave in the same way. Green fill also had the same opacity as object. You want to reduce opacity of objects, but don't want to reduce opacity when button is pressed? If so my solution above will not help.

About different color, you will need to adjust javascript code. Find functions `setButtonPressed` and `setButtonUnpressed`. Instead of `element.style.fill = buttonPressedColor;` you can use:
```
if (element.id == 'ButtonA') {
    element.style.fill = '#123456';
}
if (element.id == 'ButtonB') {
    element.style.fill = '#7890AB';
}
// and so on
```

About CPU/GPU usage. My program relies completely on Browser Source in OBS, and we have no control over its settings. You can also have performance problems with it, especially if you try to use complex and beautiful SVG animations.
