### ISSUE TITLE
Files are 404-ing after first use

### ISSUE THREAD

**Issue by pjmdesi** [Zergatul/Zergatul.Obs.InputOverlay#13]
Hi there, I'm getting an error where the overlay terminal is showing everything but the mouse file as 404-ing after the first time they are used.

If I build and open, the very first time, everything loads just fine. I can use the keyboard and mouse viewer. But if I close the app and lunch it again, any other file except the mouse file 404s.

![image](https://github.com/Zergatul/Zergatul.Obs.InputOverlay/assets/36543053/1ba6e881-9949-4777-b2fa-bbeaaa225e4b)

**Comment by Zergatul** [comment]
On your screenshot it says `Content root path: C:\WINDOWS\system32`
Somehow you are starting the app with system32 as current directory. App is looking for files in this directory.

**Comment by pjmdesi** [comment]
@Zergatul 
That's weird because I am definitely running the app from a completely different location, different drive even. Also it doesn't explain why the mouse one still works, or why the keyboard ones did work the very first time I ran the app.

I assumed the app copied the files temporality to that location.

**Comment by Zergatul** [comment]
@pjmdesi App doesn't copy any files. My best guess is OBS cached all static files, and only use websocket connection when communicating with app.

Maybe you created link, or maybe because you are starting is as admin it starts in system32. Anyway, app doesn't control its current directory.

**Comment by pjmdesi** [comment]
@Zergatul 
I guess I don't understand why the app is using system32 as the root location how do I change that?

**Comment by pjmdesi** [comment]
Never mind, I figured it out!

I was using the wrong version, I needed to use the one under the "publish" folder. I was using the one in that folder's parent. Not sure how I ended up with 3 different versions... ¯\\\_(ツ)\_/¯

**Comment by pjmdesi** [comment]
Okay, so actually that wasn't the problem. Turns out that all 3 versions use the correct root directory _only if_ I launch the app using the file in the folder. If I try to launch it from a shortcut, or from my stream deck, then it uses **system32** as root for some reason. I have no idea why this is the case, but I guess I can just launch it from the folder for now.

I hope this can be fixed.

**Comment by Zergatul** [comment]
Shortcuts have field "Start in". This is current directory for process it starts. Check it

**Comment by pjmdesi** [comment]
@Zergatul 
Checked the Start in field, and it is pointing to the correct directory.
For some reason the shortcuts are working now and I am unable to recreate the issue. Hopefully it was just a fluke.
