### ISSUE TITLE
Help: Dual PC Issue

### ISSUE THREAD

**Issue by migeru-san** [Zergatul/Zergatul.Obs.InputOverlay#2]
First of all, I LOVE this project! I have been using it on my streams on my gaming PC, however, I just switched to Dual PC (Stream PC + Gaming PC)

is any way I can make this work/ show on my streaming PC to connect to OBS?

I've tried the following:
*ran the .exe on both pc but my streaming pc but It doesn't track the inputs and also I put "http://localhost:5001/mouse.html" on obs

* I try a software called MouseWithoutBorders, it works but only when focusing on the Streaming PC, any help??

**Comment by Zergatul** [comment]
You can try this and let me know if it works:
https://obsproject.com/forum/threads/input-overlay-plugin-based-on-html.144327/#post-550420

**Comment by migeru-san** [comment]
Cool someone else was asking for this, but tbh I do not know how to do this part _"Imagine you need to run server at 192.168.1.123:12345"_

the rest I think I can do it,


_"Why do you need this? Maybe it worth for me to add change/instructions and make it easier."_ **maybe this person having my issue.**

**Comment by Zergatul** [comment]
192.168.1.123 is IP of your gaming PC. You can choose any port you want, default port if 5001 (this is when you use http://localhost:5001/...). In my example port is 12345.

**Comment by migeru-san** [comment]
I did edit the text:
_**1. Find line in engine.js: var ws = new WebSocket('ws://localhost:5001/ws'); and change it to: var ws = new WebSocket('ws://192.168.1.123:12345/ws');**_
![image](https://user-images.githubusercontent.com/68115458/146484333-d345b776-427a-4071-a318-39c09f32a017.png)

I did this:
**_2. Run executable with parameter: Zergatul.Obs.InputOverlay.exe --urls http://192.168.1.123:12345/_**

![image](https://user-images.githubusercontent.com/68115458/146483459-6513b749-fc60-4a7f-aa06-4a79affa8fdd.png)

This is what it says after I run the executable:

> info: Zergatul.Obs.InputOverlay.InputHook[0]
>       Hook set: 0x000000001a2d0bc9
> info: Zergatul.Obs.InputOverlay.InputHook[0]
>       Hook set: 0x0000000020a00c19
> crit: Microsoft.AspNetCore.Server.Kestrel[0]
>       Unable to start Kestrel.
> System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
>    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
>    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
>    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
>    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
> info: Zergatul.Obs.InputOverlay.InputHook[0]
>       Hook released.
> info: Zergatul.Obs.InputOverlay.InputHook[0]
>       Hook released.
> Unhandled exception. System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
>    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
>    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
>    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
>    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
>    at Zergatul.Obs.InputOverlay.Program.Main(String[] args)
>

**Comment by migeru-san** [comment]
![image](https://user-images.githubusercontent.com/68115458/146489611-b8a29358-b0be-4309-8c61-ec020e7dc7e6.jpeg)

**Comment by Zergatul** [comment]
You should find out what is IP of your gaming PC in your local network. You cannot just use `192.168.1.123` from my example. Start command line, run `ipconfig` and find correct IP.

**Comment by migeru-san** [comment]
lmao smh I am dumb, got it,  now it says is listening to the ip

Only the keyboard is being detected,` the mouse is not working` btw this is fucking awesome!! xD

**Comment by Zergatul** [comment]
Check again Browser Source settings for mouse. Maybe something is wrong. Try hide/show. Check application log (every time your Browser Source access some url, you see requests coming in log).

**Comment by migeru-san** [comment]
I refreshed but nothing, I wonder what it when wrong, do you have a discord?

**Comment by Zergatul** [comment]
Zergatul#8135

**Comment by Zergatul** [comment]
Instructions have been added to README, and the process of configuring dual PC was simplified in version 1.0.3
