### ISSUE TITLE
Question: Customizing the mouse

### ISSUE THREAD

**Issue by migeru-san** [Zergatul/Zergatul.Obs.InputOverlay#3]
I tried to customize the "mouse.svg" to match Logitech G502 HERO but I doesn't really look okay, I use Adobe Illustrator for it

Do you think you can help me?

**Comment by Zergatul** [comment]
I don't know much about svg. I draw my mouse in Inkscape. I gave id's to all buttons, made transparent background, and lines color is white. In Inkscape there is option "Save optimized svg", in Illustrator it may be called "Save for web" or something like this. Then I copied svg file content into mouse.html.
What kind of issues you have with your svg?

**Comment by migeru-san** [comment]
That might be the problem, since Inkscape gives different coordinates than Illustrator, I will do a test!

as far as the issue, it looks all messy lol, I just modified the looks and keep the same names so it doesn't mess up with the coding.

**Comment by Zergatul** [comment]
Docs about customizing has been added https://github.com/Zergatul/Zergatul.Obs.InputOverlay/blob/master/docs/CustomizingMouse.md
