### ISSUE TITLE
Improvements: Scroll Wheel dectection?

### ISSUE THREAD

**Issue by migeru-san** [Zergatul/Zergatul.Obs.InputOverlay#4]
I will do a video illustration maybe this feature can be added

**Comment by migeru-san** [comment]
https://user-images.githubusercontent.com/68115458/146466159-c8463bea-b7b9-449f-a14d-4396d8c287be.MOV

I could have done a better job with the animation but I just want to show it to you if is possible.

**Comment by Zergatul** [comment]
In current version this is not possible. I will have to make code changes.

**Comment by Zergatul** [comment]
Mouse scroll support added in version 1.0.3
