### ISSUE TITLE
Feature request: gamepad support

### ISSUE THREAD

**Issue by Nomad7** [Zergatul/Zergatul.Obs.InputOverlay#6]
Personally I'm specifically interested in the Xbox 360 controller, Steam controller, and Thrustmaster T.Flight HOTAS 4 - but that's because I'm a selfish person and those are the controllers I own. :)

I mentioned this in #5 already but it's worth saying again: your overlay is good and you should feel good for making it. Thank you!

**Comment by Zergatul** [comment]
I have added support of gamepad in new release. I tested it with my XBox Series X|S Controller, but it should work fine with 360. It may also work with Steam controller, you can try (but touch pad is not supported).

**Comment by Nomad7** [comment]
Did some brief testing with my 360 controllers - it looks like if both the right and left triggers are held down at the same time neither one will light up. They work fine independently, and if I have for example right trigger fully pressed and start to slowly press left trigger, the right trigger highlight will fade to dark.
Seems like maybe they're acting as opposite ends of an axis, so fully depressing both displays as 'neutral' but that's just my guess :)

I seem to have misplaced my Steam controller dongle but if I can find it I'll do a little testing there too.

Is there a way to have two separate overlays for two separate gamepads? This is probably outside the scope of the original request so if it makes more sense to be a separate ticket let me know, but I sometimes play co-op games with my kids and being able to show multiple controllers would be pretty cool. :)

**Comment by Zergatul** [comment]
That is what gamepad driver reports, these triggers act like single axis, and driver reports single value. I will investigate if it possible to change "mode" and say driver to report data in a different way. It seems like some games use triggers as independent buttons, and can understand when player hold them both.

I implemented support for multiple gamepads, check https://github.com/Zergatul/Zergatul.Obs.InputOverlay#advanced-usage , paragraph 6. However HDevice will change if you restart PC, and probably if you turn off/on gamepads. Maybe I should find a better way to identify gamepads.

BTW we came up with better design for gamepad overlay, you can try it out (but these changes are not in the main branch yet). Download `default-gamepad.html` and `XBoxSeriesXController.svg` from here https://github.com/Zergatul/Zergatul.Obs.InputOverlay/tree/feature/gamepad/src/wwwroot

**Comment by Nomad7** [comment]
Oh the triggers really do share an axis? Interesting!
> some games use triggers as independent buttons, and can understand when player hold them both

This is what confused me, I assumed they could be recognized separately, no idea how difficult it would be to do that though. Not sure how common it is to be pressing both triggers at once anyway, just seemed odd that pressing a 2nd trigger un-pressed the 1st :)

> https://github.com/Zergatul/Zergatul.Obs.InputOverlay#advanced-usage , paragraph 6

Whoops, I must have missed that, thanks! That's probably sufficient for my purposes, although having to reconfigure it every reboot and any time controller plugs are changed is unfortunate :p

> better design for gamepad overlay

Wow I just checked it out (had to change the object reference at the bottom of the html) and that's way better, much better use of the space! I feel like the triggers could maybe even be slightly smaller, but since they shrink down when pressed (cool animation btw) it all fits together nicely.

**Comment by Zergatul** [comment]
You can check in gamepad settings in Windows, that 2 triggers share single axis, called Z. Open "Bluetooth & other devices", scroll down to "Related Settings", click "Devices and printers", right click on gamepad, select "Game controller settings", select controller and click "Properties". It displays all axes and buttons reported by driver.

Thanks for sharing feedback!

**Comment by Zergatul** [comment]
You can check new release. If you have XInput compatible gamepad (like any XBox gamepad), you can use `XBoxSeriesX-XInput.html`. Also it is much simpler to use multiple gamepads with XInput. I updated docs: https://github.com/Zergatul/Zergatul.Obs.InputOverlay/blob/master/docs/MultipleGamepads.md

**Comment by Nomad7** [comment]
I've been meaning to try this with all 4 of my controllers (three 360 controllers and one Steam controller) but I've misplaced the dongle for my Steam controller, and then got sidetracked with other things - sorry for the belated response! 

Anyway, at least with 2 Xbox 360 controllers using the XInput configuration method this appears to be working great! The shoulder triggers display individually and simultaneously without issue.

One issue I noticed is that it looks like if I have a gamepad overlay configured (but not active) in OBS but no gamepad plugged in at the moment I run Zergatul.Obs.InputOverlay.exe the overlay crashes.

Steps to reproduce this:
1. Configure gamepad overlay(s) in OBS
2. Close InputOverlay.exe, close OBS, unplug all controllers
3. Launch OBS
4. Launch InputOverlay.exe

Expected result: InputOverlay should run without crashing; gamepads should display properly once plugged in

Actual result: InputOverlay crashes after displaying the following message:
`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Zergatul.Obs.InputOverlay.XInput.XInputHandler.PollingThreadFunc() in C:\Users\Zergatul\source\repos\Zergatul.Obs.InputOverlay\src\XInput\XInputHandler.cs:line 70`

**Comment by Zergatul** [comment]
Thanks for the error log message. I found small bug, but I still don't believe it can cause crash (I assume chances should be 1 in 1000). You can check new release and let me know.

**Comment by Nomad7** [comment]
Not sure if it counts as a crash exactly, or what was happening... but on 2.2.0 if I try to run the overlay .exe with OBS already started and no gamepads plugged in, it shows that error and then closes itself a few moments later. 

Anyway, 2.2.1 fixes that problem so everything's great now! I'll check out that 4-player scenario sometime once I get my Steam controller working again, but at this point gamepad support is excellent as far as I can tell.

Thanks once again for your awesome work, I've been using your overlay on 99% of my gameplay videos and I have zero complaints, really great stuff. :)

**Comment by Zergatul** [comment]
Good!
May I ask, when you had problem with 2.2.0, did you have high CPU game running in background along with OBS? Do you use Windows 10 or 11? What is your CPU model?
We tested 2.2.0 version with no gamepads, on 3 different systems many times and this bug never appeared.

**Comment by Nomad7** [comment]
Oh interesting - I may have had a couple things running at the time, including an idle game I often have in the background, but CPU usage should have been below 30% I think.

My specs:
Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz   3.79 GHz
16GB RAM
Win10 Home x64

2.2.1 has been working flawlessly so far, but I'm happy to help do any additional troubleshooting on 2.2.0 if that would be helpful, just let me know. :)
If you're on discord feel free to message me @ Nomad#6589 for quicker responses, I don't check my email very often :p

**Comment by Zergatul** [comment]
Thanks! No need for additional testing 2.2.0, there was a bug and we fixed it. This is just my curiosity :)
