### ISSUE TITLE
Problem: Cant connect 2 pcs

### ISSUE THREAD

**Issue by CTRQuko** [Zergatul/Zergatul.Obs.InputOverlay#9]
Hi, I found your repo looking for a solution for a dual stream overlay, following the steps you indicate I can not get my stream pc to access the html of the keyboard or mouse on the gaming pc. I attach screenshots and my configuration, I start the program with a .bat to simplify I use this command:

D:\OBS.Obs.InputOverlay.2.2.0.win64\Zergatul.Obs.InputOverlay.exe --urls http://192.168.1.2:1000

My firewall has a rule configured for access to that port.

I use remote desktop to access the stream pc and every access attempt sends error 404.

![Captura de pantalla 2022-02-05 160851](https://user-images.githubusercontent.com/99084921/152647469-a444e815-a28b-4675-b0c0-ed80c062418d.png)

I tried to add to the end of the path of the game pc ip /default-keyboard.html and the console shows an error and closes. I understood that the access to a web was missing so that it did not show error 404.
![Captura de pantalla 2022-02-05 161637](https://user-images.githubusercontent.com/99084921/152647709-8eea3998-f10c-487b-b25c-739e21da2571.jpg)

**Comment by Zergatul** [comment]
It looks like on you screenshot current directory is `C:\Windows\system32`.  Check log records for "Content root path".

Current directory should be directory of executable. It is looking for wwwroot folder in current directory, and it doesn't exist in your case. If you are getting 404, that means there is no firewall issues.

**Comment by CTRQuko** [comment]
thanks for answering so fast, I fixed the .bat but I don't get results, do I have to add to the path the .html of the keyboard?

**Comment by Zergatul** [comment]
What do you mean by "don't get results"? You have to use URLs with .html files, you can't just use `http://192.168.1.2:1000/`, like you did on your second screenshot.

**Comment by CTRQuko** [comment]
on the second pc adding that url to obs as a browser source as you indicate in the read.me does not show the keyboard and using chrome either.

**Comment by CTRQuko** [comment]
![Captura de pantalla 2022-02-09 162051](https://user-images.githubusercontent.com/99084921/153231693-a570a659-b123-4f30-a3b4-c0041b590416.png)

**Comment by Zergatul** [comment]
Sorry, this is not correct URL. You should request specific html file, example: `http://192.168.1.2:1000/default-keyboard.html`. You can look into wwwroot folder to see other html files you can use.

**Comment by CTRQuko** [comment]
I must have made a mistake in some point or symbol, now it works for me, thanks
